// Registry of stable public application error codes
export const PUBLIC_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

  CONFLICT: "CONFLICT",
  NOT_FOUND: "NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  INVALID_OR_EXPIRED_OTP: "INVALID_OR_EXPIRED_OTP",
  INVALID_OR_EXPIRED_TOKEN: "INVALID_OR_EXPIRED_TOKEN",

  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN_ROLE_ACCESS: "FORBIDDEN_ROLE_ACCESS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  ACCOUNT_ALREADY_LINKED: "ACCOUNT_ALREADY_LINKED",
  ACCOUNT_NOT_LINKED: "ACCOUNT_NOT_LINKED",
  CANNOT_UNLINK_SOLE_METHOD: "CANNOT_UNLINK_SOLE_METHOD",
} as const;

// Union type of all valid public error codes
export type PublicErrorCode =
  (typeof PUBLIC_ERROR_CODES)[keyof typeof PUBLIC_ERROR_CODES];
